### ISSUE TITLE
Flashing player, when using Custom 3rd person cam, while on elytra

### ISSUE THREAD

**Issue by Mudxiej** [henkelmax/camera-utils#1]
As topic says. When gliding with elytra, using Custom 3rd person cam makes player flash.
Easy to recreate having camera set close to head, and glidint with elytra at certain angle.

https://user-images.githubusercontent.com/82979937/127785511-b3d2b120-adac-450c-84ec-915160f93c35.mp4

![Zrzut ekranu 2021-08-01 231403](https://user-images.githubusercontent.com/82979937/127785518-36d23fd3-2e36-4f06-8534-89cc93a69063.png)

**Comment by henkelmax** [comment]
https://bugs.mojang.com/browse/MC-111516
