### ISSUE TITLE
Add crosshair to custom third person mode

### ISSUE THREAD

**Issue by DLandDS** [henkelmax/camera-utils#10]
as in the title

**Comment by henkelmax** [comment]
This makes no sense, as the crosshair is meant to show where the player is looking at. The player is NOT looking at the center of the screen in the custom mode, meaning this would make no sense and would confuse people.

**Comment by ardissaps** [comment]
> the

Maybe can e a little cute toggle labeled as "super secret setting". But it's ok, thanks for your time answering, great mod! :)
