### ISSUE TITLE
Incompatible with Revamped Phantoms

### ISSUE THREAD

**Issue by Fourbo** [henkelmax/camera-utils#11]
**Bug description**
The game crashes when launching with both Camera Utils and Revamped Phantoms installed. The game runs fine without Revamped Phantoms. My guess is that since Revamped Phantoms makes it so phantoms can grab the player/entities into the sky and causes the camera angle to change, that this coded camera perspective is conflicting with the Camera Utils' code.

**Steps to reproduce the issue**
1. I added Camera Utils, Architectury API,  Fabric API, and Revamped Phantoms.
2. I click the start button in Minecraft Launcher. The crash only happens when revamped phantoms is included.
3. Minecraft launcher gives the following error:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_312 failed
Exit Code: -1

**Expected behavior**
I expected the game to run fine and for the camera angle changes of the phantoms picking you up to not conflict with the custom camera angles of Camera Utils. I don't know if Revamped Phantoms uses a custom camera setting for this or if it uses a Vanilla camera angle.

**Log files**
(https://gist.github.com/Fourbo/a9a05a00c8ceb8a52aa1e6df5a32e9fb)

**Versions**
- Minecraft version: 1.18.2
- Fabric loader version: 13.3
- Mod version: camerautils-1.18.2-1.0.0

**List of mods**
architectury-4.0.30
camerautils-1.18.2-1.0.0
fabric-api-0.47.8+1.18.2
revamped_phantoms-fabric-0.2.1

**Comment by henkelmax** [comment]
This does not happen with Revamped Phantoms `v0.2.3` please update the mod.
