### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by Scorpid1** [henkelmax/camera-utils#13]
**Please read the [FAQ](https://modrepo.de/minecraft/camerautils/faq) before submitting a bug report!**

**Bug description**
The game crashes as soon as you launch it. I believe its a conflict with some other mod, as it works fine when launched with only Camera Utils and no other mods.

**Steps to reproduce the issue**
1. Launch the game
2. Game crashes

**Expected behavior**
The game should be able to launch and be playable. It was fine until I installed this mod, and works just fine when I uninstall Camera Utils.

**Log files**
[2022-04-09-6.log.gz](https://github.com/henkelmax/camera-utils/files/8458093/2022-04-09-6.log.gz)

**Versions**
- Minecraft version: 1.18.1
- Fabric loader version: fabric-0.13.3
- Mod version: camerautils-1.18.1-1.0.0.

**Other mods**
Architectury API
BetterF3
Cloth Config API
Controlling
DisguiseHeads
DisguiseLib
Fabric API
FabricTailor
Gravity Changer
Immersive Portals
MiniScaled
ModMenu
Mouse Tweaks
Pehkui
Roughly Enough Items
Skin Layers 3D
ToroHealth Damage Indicators
WorldEdit
WorldEdit CUI
Xaero's Minimap
Xaero's World Map

Crash Report listed below:
[crash-2022-04-09_21.49.20-client.txt](https://github.com/henkelmax/camera-utils/files/8458092/crash-2022-04-09_21.49.20-client.txt)

**Comment by henkelmax** [comment]
Yes. This is a conflict with `Gravity Changer`
