### ISSUE TITLE
Better support for action RPG

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [henkelmax/camera-utils#14]
**Is your feature request related to a problem? Please describe.**
I like to play in 3rd person mode, especially during combat situations.
The best way to enjoy such scenarios would be a "Over the shoulder perspective", just like many modern action oriented games do it.
This is the best mod to configure the 3rd person this, here is what I think is missing:
- option to replace default 3rd person view camera utils 3rd person view
- show crosshair in camera utils 3rd person view
- show aim helper line (like laser pointer) in 3rd person view

**Describe the solution you'd like**
- An option into the config json of the mod to replace default 3rd person view
- Show crosshair in camera utils 3rd person view
- Show aim helper line in 3rd person view (line color white by default, can be configured in config json).

**Describe alternatives you've considered**
Shoulder surfing mod, Epic Fight mod, etc... Unfortunately all of these come with Forge and or heavy serverside dependencies.

**Additional context**
I am looking to create a combat orient modpack where the "Over the shoulder perspective" would be essential.
This mod has a very strong foundation, lacks only these guidance features to be used for these kind of purposes too.

**Comment by henkelmax** [comment]
- We deliberately decided not to be able to modify the default 3rd person view
- A crosshair wouldn't make sense, since the center of the screen isn't necessarily where you are aiming
- This won't happen as it is way to complex to implement and wouldn't fit to the style of the mod

**Comment by henkelmax** [comment]
This mod is also not meant for combat.
It is meant for content creators, for better visuals and cinematics
