### ISSUE TITLE
Default controls not set

### ISSUE THREAD

**Issue by meza** [henkelmax/camera-utils#2]
**Bug description**
None of the default controls are set aside from z, F5 and F6.
R.ALT doesn't do anything as in the description of the mod.

Also, R.Alt isn't configured for anything else, it's a free key.

**Steps to reproduce the issue**
1. install the mod
2. Click on Settings->Controls
3. Scroll down to the Camera Utils part

**Expected behavior**
The documented shortcuts should be set

**Log files**
https://gist.github.com/meza/ec42c731f3742465c389213e646f5e15

**Versions**
- Minecraft version: 1.17.1
- Fabric loader version: 0.11.6
- Mod version: 1.17.1-1.0.2

**Screenshot**
![image](https://user-images.githubusercontent.com/211977/127985650-8d2166ed-8510-411e-af92-6d2a6f0241d1.png)

**Comment by henkelmax** [comment]
I can clearly see from your screenshot that every mentioned keybind is set.
Right alt is not in the controls since it is not a keybind. It is a modifier key.

**Comment by meza** [comment]
It still isn't doing anything. It's not releasing the camera AND it isn't bringing up the settings for the F5 and F6 modes

**Comment by henkelmax** [comment]
You need to press for example `RIGHT ALT` + `F6` to open the GUI.
Alternatively you can bind the `Custom Third Person Camera 1 Settings` keybind.

**Comment by meza** [comment]
I know I have to press them together, that's what the documentation says but it doesn't bring anything up.
Also, the documentation says R.Alt releases the camera which it doesn't.

**Comment by henkelmax** [comment]
You are clearly confusing the third person view with the detach camera feature.

**Comment by meza** [comment]
No, I just suck at reading...

![image](https://user-images.githubusercontent.com/211977/127988064-f86c4f49-36c0-4f90-b1b7-4740f0750824.png)

My brain saw the title, saw the key highlighted and boom. My bad, thanks for taking the time to respond.

It might be worth highlighting in the docs that you have to actually manually go and set a key, there's only defaults for a few things.
