### ISSUE TITLE
Transitioning from detached camera to custom third-person stays in detached camera POV

### ISSUE THREAD

**Issue by VoidedMirror** [henkelmax/camera-utils#20]
**Bug description**
Changing POV between Detached Camera POV and Custom Third-Person Camera 1 or 2, does not change to the new camera POV. 

**Steps to reproduce the issue**
1. Start in Custom Third-Person Camera 1
2. Press hotkey for Detached Camera.
2. Press hotkey for Custom Third-Person Camera 1.
3. Hotbar and hand are now visible as if in First-Person POV and Camera is the same as Detached Camera POV, however the player is now invisible and not actually in First-Person.

**Expected behavior**
Camera should correctly transition to Third-Person POV from Detached Camera POV.

**Log files**
https://gist.github.com/VoidedMirror/ffcb330f501e2b984abfd10d48c6638b

**Versions**
- Minecraft version 1.19
- Fabric loader version 0.14.8
- Mod version 1.19-1.0.0

**Other mods**
fabric-api-0.57.0+1.19.jar

**Comment by henkelmax** [comment]
Thanks for reporting this!
