### ISSUE TITLE
3rd person mode like Shoulder surfing

### ISSUE THREAD

**Issue by ZephaniahNoah** [henkelmax/camera-utils#21]
I was looking for something like shoulder surfing but for fabric and this was the only mod I found. However it's quite difficult to focus on blocks, entities, etc. Could you add something similar to the third person mode in shoulder surfing? Something that actually alters where the player is looking. And with a crosshair.

**Comment by henkelmax** [comment]
This is a client side mod. Its not possible/recommended to change the looking direction from the default.
This mod is also just for visual purposes.

**Comment by ZephaniahNoah** [comment]
I'm struggling to understand what you mean. Shoulder Surfing is client side. It's definitely not "impossible" to do what Shoulder Surfing already did. You should take a look if you haven't already seen it. It's a great mod. And it's open source.

**Comment by henkelmax** [comment]
I'm not planning to copy any mods.

**Comment by ZephaniahNoah** [comment]
I wasn't implying that you should copy them. Just pointing out that it isn't "impossible"
