### ISSUE TITLE
Isn't this mod client side only? I'm asking because from your Modrinth page, it says that it requires to be both in client and server

### ISSUE THREAD

**Issue by macimas** [henkelmax/camera-utils#25]
Isn't this mod client side only? I'm asking because from your Modrinth page, it says that it requires to be both in client and server
Edit: Looks like it is, judging from the FAQ. maybe fix Modrinth page?
![image](https://user-images.githubusercontent.com/42163944/182157138-aab4e5c4-0fa7-431b-a8e9-d3a5ba69b03b.png)

**Comment by henkelmax** [comment]
Oh, yeah that was an oversight by me. It should be client side only, I'll fix that.
