### ISSUE TITLE
Can see through blocks in 3rd person

### ISSUE THREAD

**Issue by Shepiock** [henkelmax/camera-utils#26]
**Bug description**
We can see through blocks in 3rd person

**Expected behavior**
Like in vanilla f5, the X Offset adapts so as not to pass through blocks

**Versions**
- Minecraft version: 1.19.1
- Fabric loader version: 0.14.8
- Mod version: 1.0.2

**Screenshots (Optional)**
Screenshots of the issue:

**3rd Person (mod)**
![2022-08-05_17 11 01](https://user-images.githubusercontent.com/64580358/183106850-59a887c7-07cf-47f0-9fc2-89ddf4f5d94d.png)
**3rd Person (vanilla)**
![2022-08-05_17 12 25](https://user-images.githubusercontent.com/64580358/183107198-e219d903-69a1-4f54-aa6a-488de160138e.png)

**Comment by henkelmax** [comment]
See #6
