### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by MithicSpirit** [henkelmax/camera-utils#29]
Not really a feature request, but please add a license (ideally a FOSS license like MIT or one of the GPLs)

**Comment by henkelmax** [comment]
The license is `All Rights Reserved`. Thats the default license if you don't provide one.

**Comment by MithicSpirit** [comment]
You should probably still add a license to the repository saying that it's all rights reserved, as reading and learning from proprietary code can be a minefield for developers.
