### ISSUE TITLE
Front-First 3rd person view

### ISSUE THREAD

**Issue by meza** [henkelmax/camera-utils#3]
As a content creator it's often difficult to make nice transitions between a "selfie" camera mode and the 1st person mode.

I would love to be able to have a setting for the custom camera modes that would make it so upon the first button press, we'd go straight into the same view as we do now on the 2nd press.

I'm right now either trying to press the button very fast OR remove the unwanted frames in editing. Both are very annoying workarounds,

**Comment by henkelmax** [comment]
This is already possible.

**Comment by meza** [comment]
Can you explain how?

**Comment by henkelmax** [comment]
Just press the inverted button.

**Comment by meza** [comment]
Found it in the meantime, thanks. First time I pressed it, it flipped the world around for some reason and I thought it just "inverts the world" :D Works now, thanks this is actually a huge time saver
