### ISSUE TITLE
Mod incompatibility 

### ISSUE THREAD

**Issue by Adriianh** [henkelmax/camera-utils#36]
**Bug description**
Crashes when meteor client is present.

**Steps to reproduce the issue**
1. Go to Minecraft
2. Join to a world/server
3. Toggle perspective
4. See error / crash

**Expected behavior**
Change the perspective without any problem.

**Log files**
https://mclo.gs/Ya689tD

**Versions**
- Minecraft: 1.19.2
- Fabric loader: 0.14.2
- Mod version: 1.0.3

**Other mods**
- Meteor Client (0.5.1)
- Fabric API (0.69.0)

**Comment by henkelmax** [comment]
I can't see anything related to the camera utils mod in your crash report. Please make sure this is actually caused by this mod.

**Comment by Adriianh** [comment]
Meteor Client support says that the problem is because of this mod, they don't want to fix anything. Anyway, thank you very much!
