### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by RDKRACZ** [henkelmax/camera-utils#4]
https://paste.ee/p/t2c5T
The game crashed while launching

**Steps to reproduce the issue**
For me, just try to launch.

**Versions**
- Minecraft version 1.17.1
- Fabric loader version 0.11.6
- Mod version 1.0.3 and 1.0.2

**Other mods**
accurate-block-placement-1.0.10
AmbientEnvironment-fabric-1.17.1-6.0.21
architectury-2.3.23-fabric
BetterThirdPerson-Fabric-1.17-1.5.0
c2me-fabric-mc1.17.1-0.2.0+alpha.3.1-all
camerautils-1.17.1-1.0.3
clear-skies-mc117-1.5.70
cloth-config-5.0.37-fabric
consistency_plus-1.17.1-0.4.0
cpas-2.0.0
crawl-0.9.1
Croptopia-1.17-FABRIC-1.6.0
custom-fog-1.6.0
DripSounds-1.17-0.2.2-no-bundled-cloth
enhancedblockentities-0.4.1+1.17
EntityCulling-Fabric-1.3.2
fabric-api-0.37.1+1.17
fabric-enchantments-0.4.1
fabric-language-kotlin-1.6.3+kotlin.1.5.21
fabrictailor-1.6.1
FpsReducer-fabric-1.21-mc1.17.1
freelook-1.1.0
hydrogen-fabric-mc1.17.1-0.3
indium-1.0.0+mc1.17.1
inventorio-1.17-fabric-1.6.2
iris-mc1.17-1.1.1
krypton-0.1.4
lambdynamiclights-2.0.2+1.17
lazydfu-0.1.2
lithium-fabric-mc1.17.1-0.7.3-SNAPSHOT
Loading-Timer-1.5.0-Beta1
minimalmenu-1.17-0.0.8
modmenu-2.0.4
mostructures-1.3.0-pre1-1.17.1
NoFog-1.17.1b1-Fabric
NorthernCompass-Fabric-1.17.1-1.0.5
notenoughcrashes-3.4.0+1.17-fabric
PerspectiveModRedux-1.17-0.0.5_01
preciseblockplacing-1.08+1.17.1
quickspyglasser-0.2.2
repurposed_structures_fabric-2.1.8+1.17.1
RoughlyEnoughItems-6.0.267-alpha-fabric
sentimentality3-1.2.9
skin-restorer-1.0.1
sodium-extra-mc1.17.1-0.3.3
spyglass-zoom-1.0.1
starlight-1.0.0-RC3+fabric.332679e

**Comment by henkelmax** [comment]
Does that happen without any other mods?
If no, please try and find out which mod in combination with camera utils causes it.
I would start with spyglass-zoom and BetterThirdPerson. These mods sound like they can conflict with this mod.

**Comment by Cynosphere** [comment]
```
[18:03:45] [Render thread/WARN]: @Redirect conflict. Skipping camerautils.mixins.json:MouseHandlerMixin->@Redirect::smoothCamera(Lnet/minecraft/class_315;)Z with priority 1000, already redirected by quickspyglasser.mixins.json:MouseMixin->@Redirect::smoothCameraEnabledRedirector(Lnet/minecraft/class_315;)Z with priority 1000
```

quickspyglasser is at fault, not PMR.
