### ISSUE TITLE
Detached camera rotation

### ISSUE THREAD

**Issue by lynrayy** [henkelmax/camera-utils#40]
How to rotate detached camera?

**Comment by henkelmax** [comment]
Thats not possible. You can just invert it (Rotate it 180°)

**Comment by lynrayy** [comment]
But how HE made it?
As i know, he have cameraUtils and PerspectiveMod (which only allow rotate camera on F5, i tried to use perspective mod - not working as in stream)
https://youtube.com/clip/Ugkx1eK7IsnNMVUwWGPwr7g7JI-v6yDLf9G_

**Comment by henkelmax** [comment]
Thats the detach camera feature.

**Comment by lynrayy** [comment]
And he rotates the camera. HOW?

**Comment by henkelmax** [comment]
I guess then its not this mod.

**Comment by lynrayy** [comment]
I want this feature in camera utils :)
