### ISSUE TITLE
Game keeps crashing whenever I got to f5 mode

### ISSUE THREAD

**Issue by GuflLmao** [henkelmax/camera-utils#41]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2023-01-25 16:48:38
Description: Unexpected error

java.lang.ClassCastException: class java.lang.Double cannot be cast to class net.minecraft.class_4184 (java.lang.Double is in module java.base of loader 'bootstrap'; net.minecraft.class_4184 is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @80ec1f8)
	at org.spongepowered.asm.synthetic.args.Args$3.set(Args$3.java)
	at net.minecraft.class_4184.args$zpa000$modifyCameraDistance(class_4184.java:1051)
	at net.minecraft.class_4184.method_19321(class_4184.java:55)
	at net.minecraft.class_757.method_3188(class_757.java:1029)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.synthetic.args.Args$3.set(Args$3.java)
	at net.minecraft.class_4184.args$zpa000$modifyCameraDistance(class_4184.java:1051)
	at net.minecraft.class_4184.method_19321(class_4184.java:55)
	at net.minecraft.class_757.method_3188(class_757.java:1029)

-- Affected level --
Details:
	All players: 10 total; [class_746['Gufl'/2961822, l='ClientLevel', x=-2.72, y=107.00, z=1.61], class_745['teamraiders11'/2897630, l='ClientLevel', x=-9.30, y=106.00, z=-46.70], class_745['zunny'/2952928, l='ClientLevel', x=10.65, y=104.25, z=-21.10], class_745['LeadingDavid'/2948482, l='ClientLevel', x=-0.07, y=103.06, z=-13.25], class_745['HomeAgate16302'/2924207, l='ClientLevel', x=0.29, y=103.06, z=-9.22], class_745['skyzzMcStan2'/2932685, l='ClientLevel', x=-6.46, y=104.00, z=-30.03], class_745['Flopsyz'/2563322, l='ClientLevel', x=37.97, y=103.00, z=-30.02], class_745['SorryButImMonkey'/2864997, l='ClientLevel', x=0.50, y=107.06, z=0.50], class_745['[ZNPC] 103344'/2, l='ClientLevel', x=0.50, y=103.06, z=-21.50], class_745['imJon_Joness'/2962006, l='ClientLevel', x=0.47, y=103.06, z=-9.81]]
	Chunk stats: 625, 313
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,107,0), Section: (at 0,11,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 6713 game time, 148848000 day time
	Server brand: Pufferfish
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, small pop and small totem.zip, GuflPVP Pure Default, Addin Official Texture Pack, replaymod_lang

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 574222432 bytes (547 MiB) / 1587544064 bytes (1514 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: Virtual Desktop Monitor
	Graphics card #0 vendor: Virtual Desktop, Inc.
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=15.39.56.845
	Graphics card #1 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x21c4
	Graphics card #1 versionInfo: DriverVersion=31.0.15.2802
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 48916.85
	Virtual memory used (MB): 14147.98
	Swap memory total (MB): 32768.00
	Swap memory used (MB): 74.39
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		betterhandbobbing: Better Hand Bobbing 1.2.2
		betterhurtcam: BetterHurtCam 1.5.2
			betterhurtcam-mc119: BetterHurtCam+mc1.19 1.5.2
		camerautils: Camera Utils 1.19.2-1.0.3
		clientcommands: Client Commands 2.7.4
			clientarguments: clientarguments 1.4.1
			multiconnect-api: MultiConnect API 1.5.10
		fabric-api: Fabric API 0.73.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.14+6e0787e690
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.13+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.23+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.4+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.15+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.0+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.32+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.40+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.0+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.1+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.6+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.34+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.3+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.33+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.34+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.4+693ffc0590
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.37+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.3+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.11+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.14+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.6+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.22+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.20+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.10+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.27+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.0+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.13+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.0+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.31+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.0+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.0+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.23+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.18+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.10+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.26+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.0+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.31+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.6+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.23+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.5+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.12
		inventoryhud: Inventory HUD + 3.4.2
		java: OpenJDK 64-Bit Server VM 17
		marlows-crystal-optimizer: Marlow's Crystal Optimizer 1.0.0
		meteor-client: Meteor Client 0.5.1
			baritone-meteor: Baritone 1.19.2-SNAPSHOT
		minecraft: Minecraft 1.19.2
		replaymod: Replay Mod 1.19.1-2.6.8
		totemcounter: TotemCounter 1.0.0+mc1.19.2
		ukulib: ukulib 0.3.0+1.19.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		whoami: Who am I? 1.0
	Launched Version: fabric-loader-0.14.12-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 528.02, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/small pop and small totem.zip (incompatible), file/GuflPVP Pure Default, file/Addin Official Texture Pack
	Current Language: English (US)
	CPU: 12x 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz

**Comment by henkelmax** [comment]
Please properly fill out the bug template.
