### ISSUE TITLE
Camera shakes uncontrollably when shaders are enabled.

### ISSUE THREAD

**Issue by mintysoup** [henkelmax/camera-utils#49]
When playing with shaders enabled, moving my camera view from side to side or looking up causes uncontrollable spinning and sometimes a game crash. Even slowly panning the camera causes a small shake/jitter in the 1st-person camera.

**Versions**
- Minecraft 1.20.1
- Fabric 0.14.21
- Mod version 1.20.1-1.0.4

**Other mods**
3d skin layers
Bobby
CIT Resewn
Cloth Config v11
Entity Model Features
Entity Texture Features
Fabric API
Iris
Lithium
Mod Menu
Presence Footsteps
Simple Fog Control
Sodium
Void Fog
Wildfire's Female Gender Mod
Xaero's Minimap

**Comment by henkelmax** [comment]
Does this also happen with just camera utils and iris?
You also forgot your logs.

**Comment by mintysoup** [comment]
No crash report comes up when it happens, so I don't have any logs to show. So far the shaking has only happened with camera utils and iris.

**Comment by henkelmax** [comment]
I don't need the crash report. I just need the `logs/latest.log`.

**Comment by mintysoup** [comment]
[latest.log](https://github.com/henkelmax/camera-utils/files/11805891/latest.log)

**Comment by henkelmax** [comment]
Does that happen with any shader?

**Comment by mintysoup** [comment]
yeah, i've tested with BSL, complimentary, and sildur's, but it seems to be most intense with astralex shaders.

**Comment by henkelmax** [comment]
Does it also happen with the internal shader?

**Comment by mintysoup** [comment]
yes, but not as bad as the other shaderpacks.

**Comment by fandziax** [comment]
It happens with shaders completely turned off too.

**Comment by mintysoup** [comment]
update on my end:
i reinstalled the mod through multimc, and it fixed the issue, however i found there was a file that was corrupting the memory allocation even after the mod was removed.
