### ISSUE TITLE
Mod Incompatibility [Camera Overhaul]

### ISSUE THREAD

**Issue by N-NNoThing** [henkelmax/camera-utils#50]
**Please read the [FAQ](https://modrepo.de/minecraft/camerautils/faq) before submitting a bug report!**
Link doesn't work

**Bug description**
Mod not compatible with Camera Overhaul mod
https://modrinth.com/mod/cameraoverhaul

**Log files**
https://gist.github.com/N-NNoThing/ef1de2d5d537a6149d211f6b04c07884

**Versions**
- Minecraft version
Minecraft 1.19.2
- Fabric loader version
fabric-loader-0.14.19-1.19.2
- Mod version
camerautils-1.19.2-1.0.3

**Comment by henkelmax** [comment]
Works perfectly fine with the latest versions of both mods.
