### ISSUE TITLE
Rotate camera around Z-Axis in third person view

### ISSUE THREAD

**Issue by JustAlittleWolf** [henkelmax/camera-utils#53]
**Is your feature request related to a problem? Please describe.**
The crosshair is offset to the side while in first person if the camera is next to the player.

**Describe the solution you'd like**
Allowing rotation along the Z-Axis for the camera would let you aim more precisely

**Comment by henkelmax** [comment]
Thats not possible with the current implementation.

**Comment by JustAlittleWolf** [comment]
Sorry, I meant the Y-Axis. Minecraft is confusing with its x, y and z axis.
