### ISSUE TITLE
camera raycasting

### ISSUE THREAD

**Issue by EnderTrekkie** [henkelmax/camera-utils#6]
in minecraft's normal third person mode, the camera is pushed closer to the player when it "hits" a block to stop x-raying, but the mod's third person mode does not do this, which i think is problematic

I would like the next version to move the camera towards the player if it is intersecting a block.

**Comment by henkelmax** [comment]
This is done on purpose, since this view is completely customized and should always stay at the same spot.
Moving the camera from an sideways offset would always look very weird.

**Comment by EnderTrekkie** [comment]
Maybe have a button in the positioning menu for collision

**Comment by henkelmax** [comment]
If you want to add raycasting feel free to create a PR.

**Comment by EnderTrekkie** [comment]
Pr?

**Comment by henkelmax** [comment]
Pull request
