### ISSUE TITLE
Fabric 1.20.4-1.0.9 is flagged by Windows Defender

### ISSUE THREAD

**Issue by coreyg142** [henkelmax/camera-utils#60]
### Bug description

Fabric 1.20.4-1.0.9 is flagged by Windows Defender as "Trojan:Script/Wacatac.B!ml"

### Minecraft version

1.20.4

### Mod version

camerautils 1.20.4-1.0.9

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

1. Download camerautils version 1.20.4-1.0.9 from either CurseForge or Modrinth.
2. Install in mods folder
3. Attempt to launch the game OR manually scan the file with windows defender
4. Observe the file gets quarantined.

### Log files

https://gist.github.com/coreyg142/eb8305e855562f7759f55318750dd696

### Screenshots

![image](https://github.com/henkelmax/camera-utils/assets/21230591/d1bdd865-95fd-4549-8b45-76f0714ce6e3)

**Comment by henkelmax** [comment]
https://www.virustotal.com/gui/file/b1e2352d5bcc749ef468a120d9b98a83fa857c17af79efa11a094b7bd5fc018a
