### ISSUE TITLE
Third Person modifier button doesnt work

### ISSUE THREAD

**Issue by Noobimation** [henkelmax/camera-utils#62]
### Bug description

The button doesnt do anything.

### Minecraft version

1.20.6

### Mod version

1.20.6-1.0.9

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

1. Enter an instance 2. Press the key assigned to the Third Person modifier

### Expected behavior

I expected the Third Person modifier menu to open

### Log files

https://gist.github.com/Noobimation/73525b66821316e3ba7f3fcd11a838a8

**Comment by henkelmax** [comment]
I tested it. Works perfectly fine. By default this is `RIGHT_ALT`+`F6`/`F7` depending on which one you want to modify.
