### ISSUE TITLE
My camera movements are laggy and buggy, only when the mod is installed.

### ISSUE THREAD

**Issue by ChritizinGaming** [henkelmax/camera-utils#63]
### Bug description

This bug have never happened before, in any previous versions. After I downloaded version 1.20.6, I've experienced this lag in my frames, when I move to look around, as I normally do, it's like my FPC becomes like a spring and then once I stop moving, it has a hard stop to it. It's hard to explain, so I made two screen recordings.

https://github.com/henkelmax/camera-utils/assets/138628072/9ef1e544-5478-4c8a-9b65-e665f1fb53eb

https://github.com/henkelmax/camera-utils/assets/138628072/5c085583-47f5-476b-a88b-28f8b8dad650

Like I said, it's hard to explain, so i hope that these two videos are helpful.

### Minecraft version

1.20.6 & 1.21

### Mod version

1.20.6-1.21

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

I just downloaded: https://modrinth.com/mod/camera-utils/version/fabric-1.21-1.0.9

And then I launched the game. The issue just happens. I don't know how.

### Log files

https://gist.github.com/ChritizinGaming/7f11e05a8a7c01b48dc5952197da6992

**Comment by henkelmax** [comment]
I am not able to reproduce this issue. Please check if this happens without other mods.

**Comment by ChritizinGaming** [comment]
> I am not able to reproduce this issue. Please check if this happens without other mods.

So just fabric and the camera utilities mod then?

**Comment by ChritizinGaming** [comment]
Okay, so I'm testing the 1.20.4 version first. 

So I've downloaded Fabric, version 1.20.4: https://modrinth.com/mod/fabric-api/version/0.97.1+1.20.4
As well as Camera Utils, version 1.20.4: https://modrinth.com/mod/camera-utils/version/fabric-1.20.4-1.0.9

Fabric Loader is still 0.15.11.

### **Here's what I happened:**

https://github.com/henkelmax/camera-utils/assets/138628072/7584412b-e12a-43f9-89f1-cce8017a6bd7


### **To recreate it, all I did was:** 

**1.** I used the **fabric-installer-1.0.0** fabric installer, and installed the **1.20.4** version, with the **0.15.11 Fabric Loader**
![Screenshot 2024-06-19 at 1 12 04 pm](https://github.com/henkelmax/camera-utils/assets/138628072/fb41952a-9605-478e-810e-4da495e1d5f9)

![Screenshot 2024-06-19 at 1 12 36 pm](https://github.com/henkelmax/camera-utils/assets/138628072/22713a88-4f9e-4062-996b-0ff3b0b033ad)


**2.** Then I went onto Modrinth and downloaded the fabric API mod as well as the Camera Utils mod, both on 1.20.4 version.

### **Screenshots**
![Screenshot 2024-06-19 at 1 13 36 pm](https://github.com/henkelmax/camera-utils/assets/138628072/7f7b14ae-3ff9-4e7e-9d0f-658a592b31ee)

![Screenshot 2024-06-19 at 1 14 42 pm](https://github.com/henkelmax/camera-utils/assets/138628072/4db38e81-0373-4190-a4b4-e4da0a0cc5c8)

![Screenshot 2024-06-19 at 1 14 55 pm](https://github.com/henkelmax/camera-utils/assets/138628072/8ba1c543-77a3-4e5c-919d-d04fb195aa53)

And as you can see on the screenshots; They're both installed correctly. 


### **Here's the log files as well:**
https://gist.github.com/ChritizinGaming/93ea5de545c32a5c8c2c2cc77d627315

Do you need me to add any other files?

I'll try with 1.20.5 as well as 1.20.6

**Comment by ChritizinGaming** [comment]
Here’s the tests for the 1.20.5 version first. 

So I've downloaded Fabric, version 1.20.5: https://modrinth.com/mod/fabric-api/version/0.97.8+1.20.5
As well as Camera Utils, version 1.20.5: https://modrinth.com/mod/camera-utils/version/fabric-1.20.5-1.0.9

Fabric Loader is still 0.15.11.

### **Here's what I happened:**

https://github.com/henkelmax/camera-utils/assets/138628072/40dea421-6fa9-4137-a34c-e89b4e15654d

Funniest thing is, when I use the zoom in function, the camera movement seem to not be so bad. But once I let go of my key bind for the zoom function, then my camera movements are super janky.

Same thing goes for the 1.20.4 version, I just forgot to add it into the video.


### **To recreate it, all I did was:** 

**1.** I used the **fabric-installer-1.0.0** fabric installer, and installed the **1.20.5** version, with the **0.15.11 Fabric Loader**

### **Screenshots**

![Screenshot 2024-06-19 at 2 08 02 pm](https://github.com/henkelmax/camera-utils/assets/138628072/4dd134f9-db37-4500-b1a0-06d1e849dd40) 


**2.** Then I went onto Modrinth and downloaded the fabric API mod as well as the Camera Utils mod, both on 1.20.5 version.

### **Screenshots**

![Screenshot 2024-06-19 at 2 08 52 pm](https://github.com/henkelmax/camera-utils/assets/138628072/8ec4fe4c-91c1-472c-b07e-a3f1d5cd7a37)


And as you can see on the screenshots; They're both installed correctly. 


### **Here's the log files as well:**
https://gist.github.com/ChritizinGaming/1cd9775a45525d209befa0d2dd91d9a4


### **My Mac Specs:**
I don't know if this is useful to you, but I thought it can't hurt to add this info :-)

- MacBook Pro (Retina, 13-inch, Early 2015)

- Processor: 2,7 GHz Dual-Core Intel Core i5

- Memory: 8 GB 1867 MHz DDR3

- Graphics: Intel Iris Graphics 6100 1536 MB


I'm not adding a comment for the 1.20.6, because as I wrote in my initial report, the camera movement iusse also happens for 1.20.6


Do you need me to add any other files?


Also, I have discord, **Username: ChritizinGaming**, as well as I'm a member of the Simple Voice Chat Discord, if you want to discuss this further over a call. 

My thinking is that is easier to show what files I have etc. over a call with screen sharing enabled. This way you can directly see what happens. Hence my reason for mentioning Discord.

**Comment by henkelmax** [comment]
That might be an issue on Macs then. I'll try to investigate. 
Did you do a completely fresh install or did you use the same instance? Please try to reset (delete) the config of the mod

**Comment by Warlock-1** [comment]
> That might be an issue on Macs then. I'll try to investigate. Did you do a completely fresh install or did you use the same instance? Please try to reset (delete) the config of the mod

i'm having the same issue on Windows 10, 1.20.4. but only when i have 40fps or lower, the issue becomes more and more pronounced the lower fps i have. at 10 fps the game quickly crashes. i made a fresh 1.20.4 install with just fabric and camera utils and it doesn't happen, so i'm guessing one of my other mods is causing issues
