### ISSUE TITLE
MacOS doesn't have RIGHT ALT.

### ISSUE THREAD

**Issue by Vitkek** [henkelmax/camera-utils#64]
### Bug description

Tried mashing any key on my Mac keyboard and I can't open up the menu with RIGHT ALT. You should add a keybind for opening the menu, otherwise people like me can't edit the camera without going into Config file. Thanks

### Minecraft version

1.20.1

### Mod version

1.20.1-1.0.5

### Mod loader and version

Fabric API 0.90.4 with Sinytra Connector & Forge 47.1.3

### Steps to reproduce

1. Try pressing RIGHT ALT on Mac keyboard

### Log files

None

**Comment by henkelmax** [comment]
Doesn't it work with the right option key?
