### ISSUE TITLE
My laptop doesn't have a right alt key.

### ISSUE THREAD

**Issue by Caitrix** [henkelmax/camera-utils#67]
### Bug description

I have tried to change the keybind in the config file but it changes back to right alt when starting the game.
May I suggest an option to change the keybind ingame?

(I'm sorry for ubusing the bug report but when opening an issue I could only chose between reporting a but or a translation.)

### Minecraft version

1.21

### Mod version

1.21-1.0.11

### Mod loader and version

Fabric 0.15.11

### Steps to reproduce

-

### Log files

-

**Comment by henkelmax** [comment]
Set `modifier_key` to `CTRL`.
