### ISSUE TITLE
[Suggestion] Movable detached camera

### ISSUE THREAD

**Issue by Caitrix** [henkelmax/camera-utils#68]
### Bug description

May I suggest an option to move the detached camera around?
I couldn't find an option for this. Or have I overlooked something?

(I'm sorry for ubusing the bug report but when opening an issue I could only chose between reporting a but or a translation.)

### Minecraft version

1.21

### Mod version

1.21-1.0.11

### Mod loader and version

Fabric 0.15.11

### Steps to reproduce

-

### Log files

-

**Comment by henkelmax** [comment]
https://modrinth.com/mod/freecam
