### ISSUE TITLE
No smooth camera option in accessibility settings 

### ISSUE THREAD

**Issue by TrickyFlash** [henkelmax/camera-utils#69]
### Bug description

No smooth camera option in accessibility settings 

### Minecraft version

1.21 

### Mod version

1.21 fabric

### Mod loader and version

 fabric

### Steps to reproduce

No smooth camera option in accessibility settings 

### Expected behavior

ignore log file

### Log files

https://gist.github.com/TrickyFlash/e1f35d1e6df1616c0752240c5df5b605

### Screenshots

![image_2024-07-15_032458626](https://github.com/user-attachments/assets/aa2726c2-350e-4ac2-80f8-fd7e7a7379a5)

**Comment by henkelmax** [comment]
This option has been removed due to some issues.

**Comment by henkelmax** [comment]
You can still access it from the config if you really want to use it. I'd not recommend it though.

**Comment by TrickyFlash** [comment]
Thank you!
