### ISSUE TITLE
Look around camera wobble.

### ISSUE THREAD

**Issue by waynestir** [henkelmax/camera-utils#74]
### Bug description

mouse movement is compromised.  when looking around the mouse will dance back and forth multiple times before coming to rest.  The faster the camera pan around the more severe the resulting wobble.
I'm sure my description will confuse so I will link a short YouTube video clip demonstrating.
https://youtu.be/jQbZv6f3sCI

### Minecraft version

1.20.6

### Mod version

1.0.9 & 1.0.12

### Mod loader and version

fabric 0.15.11

### Steps to reproduce

1 load into any game single player or multiplayer doesn't matter.
2 spin move crosshair in any direction then stop movement

### Expected behavior

movement to be smooth and precise not dance around when input stops.

### Log files

https://gist.github.com/waynestir/cba0c1d67bd5d28d925bb269b9bff61b

**Comment by henkelmax** [comment]
This minecraft version is no longer supported, sorry.
