### ISSUE TITLE
Player unrenders when using elytra far from camera

### ISSUE THREAD

**Issue by dbrighthd** [henkelmax/camera-utils#76]
### Bug description

On servers, players are rendered further away than other entities, but when the camera is detached with camerautils, the player stops being rendered at a closer distance than other players when the elytra is open.

### Minecraft version

1.21

### Mod version

1.21.1-1.0.16

### Mod loader and version

Fabric loader 1.16.2

### Steps to reproduce

Press detach camera button
move far away
open elytra

### Expected behavior

player should stay rendered even after opening elytra

### Log files

https://gist.github.com/dbrighthd/350978b507bd6f23653eabb8e30104db

**Comment by henkelmax** [comment]
I think this is a vanilla minecraft bug. this even happens when flying in vanilla third person when flying with the elytra.
