### ISSUE TITLE
[Suggestion/Accesibility Issue] Allow Modifier Key, Right-Alt, to be rebound

### ISSUE THREAD

**Issue by framedragged** [henkelmax/camera-utils#77]
### Bug description

It isn't possible to rebind the modifier key. I use right-alt as my jump key so this makes using camera-utils awkward and results in the settings popping up when I try to jump simultaneous with a camera switch. I'm aware that the behavior is hard coded in KeyEvents.java, but it strikes me as rather odd that this behavior is written in stone or can't at least be disabled. 

### Minecraft version

1.20.1

### Mod version

1.20.1

### Mod loader and version

Fabric Loader 0.16.5

### Steps to reproduce

It's the expected behavior of the mod. It's also unchangeable by modifying the camerautils.properties file (though I could perhaps set that to read only and carve my own settings into stone). 

### Expected behavior

It would just be nice if this feature could be either disabled or rebound. 

### Log files

https://gist.github.com/framedragged/723d90a1eda3c4218fccc6eed7337b4d

**Comment by henkelmax** [comment]
That's already a config option

**Comment by framedragged** [comment]
If that is already a config option then I have an actual bug report, as that is not present in my instance. 
![ConfigOptions](https://github.com/user-attachments/assets/1109971b-1f29-4127-87bb-e103caae2158)
![ConfigOptions2](https://github.com/user-attachments/assets/3fc04cfc-698f-4e2f-ac23-6979660adf8e)

**Comment by henkelmax** [comment]
I said config option, not keybind settings. Its in the config file.

**Comment by framedragged** [comment]
Thanks for these replies, I'm not trying to be difficult and I really appreciate you taking the time to respond. 

Is the config file not /config/camerautils/camerautils.properties? Because that's the only config file I can find and I mentioned in my initial post that I am unable to change the modifier_key value in this file because it is immediately overwritten back to RIGHT_ALT when the game is launched. I can change this file to read only, which prevents it from being overwritten, but it doesn't actually modify the behavior in game, as the pop up still occurs when I hold right-alt and activate the alternative cameras. Is there a different config file which I'm unaware of or is it possible the hard coded behavior in KeyEvents.java might still be taking precedence over this?

**Comment by henkelmax** [comment]
The only valid options for this value are `RIGHT_ALT` and `CTRL`

**Comment by framedragged** [comment]
Ah! That did the trick, thank you very much for the information!

**Comment by kallmetony** [comment]
@henkelmax can you please change mod description and explicitly say that the only valid options are `CTRL` and `RIGHT_ALT` since fabric 1.20.1 doesnt have config screen
![image](https://github.com/user-attachments/assets/f97b65b1-4e2d-4f23-b31a-57a30ba09b0e)
