### ISSUE TITLE
FOV Issue

### ISSUE THREAD

**Issue by realKeehan** [henkelmax/camera-utils#9]
**Bug description**
When using an item or effect that increases speed such as soul speed on soul sand or a speed attributing items that increase speed. My FOV increases beyond use and often flips the view upside down. I tested it without the mod and it doesn't happen. Also FOV increase randomly stops when sprinting

**Steps to reproduce the issue**
1. Give yourself this item:
 `/give @p leather_boots{display:{color:16711680},AttributeModifiers:[{AttributeName:"generic.movement_speed",Name:"generic.movement_speed",Amount:5,Operation:2,UUID:[I;928637954,-692565914,-1091907673,1001261099],Slot:"feet"}]} 1`
2. Wear them and see the effect

**Expected behavior**
Slight FOV increase, not this massive one

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version 1.17.1
- Fabric loader version Latest 0.7.4
- Mod version Latest

**Other mods**
A list of the other mods that were installed when this problem occurred.
It would be ideal if you could test if this problem persists when no other mod is installed.
If not, please narrow down the mod(s) that are causing the problem.

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
I am not able to reproduce your issue.
Your issue is missing a couple of things:
- Your logs
- The mod version (Latest doesn't say anything since this would change if I release a new version!)
- Your fabric loader version is heavily outdated (latest is 0.12.5 I think)
- The list of installed mods

**Comment by henkelmax** [comment]
Closed due to inactivity.
